### ISSUE TITLE
TypeError: Cannot set property 'comment' of undefined

### ISSUE THREAD

**Issue by really4you** [yanthink/blog-v2#2]
start后打开后显示这样，之前没用过react，之前因为node的版本问题，最开始都没有安装上，请问这是什么情况？安装过程还有其他地方需要注意的吗，谢谢。
![image](https://user-images.githubusercontent.com/17646890/65869258-ad20d180-e3ac-11e9-9b41-d01af92124e4.png)

**Comment by yanthink** [comment]
这个是 [babel-plugin-prismjs](https://github.com/mAAdhaTTah/babel-plugin-prismjs/issues/22) 插件的 bug，在少数 windows 系统下会出现，目前应该是修复了。
