### ISSUE TITLE
安装后npm start 不请求api 

### ISSUE THREAD

**Issue by kzabc** [yanthink/blog-v2#3]
![image](https://user-images.githubusercontent.com/42925731/75209813-3d2b4180-57ba-11ea-9219-891201d81829.png)
![image](https://user-images.githubusercontent.com/42925731/75209871-68ae2c00-57ba-11ea-8857-0a2e4b6c1c85.png)
不知道什么原因， 请教下大佬是那块出了问题

**Comment by yanthink** [comment]
不好意思，最近一直在忙别的事情，没注意看issues。

**Comment by yanthink** [comment]
请问这个问题你后来解决了吗？

我这两天刚把这个项目umi升级到3.2，如果你的问题没有解决可以拉取最新的代码试一下。
